# Change these first
owner: nanhosting # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: nanhosting.ch
    url: https://nanhosting.ch
  - name: nanosite.ch
    url: https://nanosite.ch
  - name: maccatattoo.ch
    url: https://maccatattoo.ch
  - name: protokoll-studio.com
    url: https://protokoll-studio.com
  - name: snapwin
    url: https://snapwin.it
  - name: reboard.io
    url: https://reboard.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nanhosting.ch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: nanhosting
  introTitle: "**nanhosting** is a nano hosting provider for small websites."
  introMessage: This is our status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
