# Change these first
owner: nanhosting # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: 96gfn.ch
    url: https://96gfn.ch
  - name: a-projectstudio.ch
    url: https://a-projectstudio.ch
  - name: assafi.org
    url: https://assafi.org
  - name: auxdelicesdelagare.ca
    url: https://auxdelicesdelagare.ca
  - name: ballissima.ch
    url: https://ballissima.ch
  - name: beachtown.ch
    url: https://beachtown.ch
  - name: bulle-detente.ch
    url: https://bulle-detente.ch
  - name: but-first-relax.ch
    url: https://but-first-relax.ch    
  - name: diotimagrossert.com
    url: https://diotimagrossert.com
  - name: do.min.icu
    url: https://do.min.icu    
  - name: dominiqueantenen.ch
    url: https://dominiqueantenen.ch
  - name: expandmarketing.ch
    url: https://expandmarketing.ch   
  - name: faki-ongd.ch
    url: https://faki-ongd.ch
  - name: hoomau.ch
    url: https://hoomau.ch
  - name: impro-impact.ch
    url: https://impro-impact.ch
  - name: improcastel.ch
    url: https://improcastel.ch      
  - name: if8.io
    url: https://if8.io 
  - name: joaouchoa.ch
    url: https://joaouchoa.ch      
  - name: judoclubaubonne.ch
    url: https://judoclubaubonne.ch      
  - name: judoclubcossonay.ch
    url: https://judoclubcossonay.ch
  - name: judoclubstadelausanne.ch
    url: https://judoclubstadelausanne.ch         
  - name: julian-bader.ch
    url: https://julian-bader.ch       
  - name: kaje.ch
    url: https://kaje.ch   
  - name: learnitevent.ch
    url: https://learnitevent.ch
  - name: maccatattoo.ch
    url: https://maccatattoo.ch   
  - name: marcbohren.com
    url: https://marcbohren.com   
  - name: mcsprint.ch
    url: https://mcsprint.ch   
  - name: mg24.ch
    url: https://mg24.ch
  - name: morphotonix.com
    url: https://morphotonix.com
  - name: nadiadedonno.ch
    url: https://nadiadedonno.ch
  - name: nanhosting.ch
    url: https://nanhosting.ch         
  - name: nanosite.ch
    url: https://nanosite.ch
  - name: nicowind.ch
    url: https://nicowind.ch         
  - name: ninn.ch
    url: https://ninn.ch
  - name: osteoneuchatel.ch
    url: https://osteoneuchatel.ch      
  - name: osteosolothurn.ch
    url: https://osteosolothurn.ch  
  - name: pixpakal.com
    url: https://pixpakal.com   
  - name: protokoll-studio.com
    url: https://protokoll-studio.com
  - name: raitone.com
    url: https://raitone.com
  - name: reboard.io
    url: https://reboard.io  
  - name: snapwin.it
    url: https://snapwin.it
  - name: somewhere.photo
    url: https://somewhere.photo      
  - name: sunset-massages.ch
    url: https://sunset-massages.ch      
  - name: travelerandco.ch
    url: https://travelerandco.ch        
  - name: valerio-personeni.com
    url: https://valerio-personeni.com      
  - name: vngl.ooo
    url: https://vngl.ooo    
  - name: watermarkme.io
    url: https://watermarkme.io      
  - name: yoma-design.ch
    url: https://yoma-design.ch   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nanhosting.ch
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/89687463?s=200&v=4
  name: nanhosting
  introTitle: "**nanhosting** is a nano hosting provider for small websites."
  introMessage: This is our status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
